# Generated by Django 4.2.4 on 2024-02-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enhancer', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('cricket', 'Cricket'), ('music', 'Music'), ('dance', 'Dance')], max_length=20),
        ),
    ]
