# Generated by Django 4.2.4 on 2024-02-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enhancer', '0003_customuser_age_customuser_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(max_length=100),
        ),
    ]
